@startuml
class ShipDesign {
  +create_components()
}
class ThrusterSlot {
  +orientation
  +position
}
class TurretSlot {
  +size
  +type
  +cone_of_fire
}

ShipDesign "1" *-- "1" Hull
Hull "1" *-- "1" Attributes
Hull "1" *-- "1" Buffs
Hull "1" *-- "many" ModuleSlot
ModuleSlot <|-- SystemSlot
ModuleSlot <|-- ThrusterSlot
ModuleSlot <|-- TurretSlot
Module <|-- System
Module <|-- Weapon
Module <|-- Thruster
Module "1" *-- "1" Attributes
Module "1" *-- "1" Buffs
SystemSlot "1" *-- "1" System
ThrusterSlot "1" *-- "1" Thruster
TurretSlot "1" *-- "1" Weapon
System <|-- PowerGenerator
System <|-- ShieldGenerator
@enduml
